### ISSUE TITLE
Define every type with TypeScript - Definir todos os tipos com TypeScript

### ISSUE THREAD

**Issue by luis-saes** [luis-saes/generic-dashboard#11]
EN:
In some code snippets, when defining the type of the variable/parameter, the TypeScript `any` type is being used.
- Change the code to receive the correct type

example:
Change from:
![image](https://user-images.githubusercontent.com/55040458/184791157-74f1363d-5c15-4018-b8e7-a70438ccd184.png)
To:
![image](https://user-images.githubusercontent.com/55040458/184791181-68fbf8c9-a133-49b7-8fef-ee98540f3911.png)

recommendation: use some IDE/Text Editor tool to find all occurrences of using `any`. In VSCode it is possible to perform this search through the magnifying glass:
![image](https://user-images.githubusercontent.com/55040458/184791392-521627b4-ec31-4551-9bd0-87f9d0db5062.png)

PT:
Em alguns trechos de código, ao definir o tipo da variável/parâmetro, o tipo `any` do TypeScript está sendo utilizado.
- Alterar o código para receber o tipo correto

exemplo:
Alterar de:
![image](https://user-images.githubusercontent.com/55040458/184791157-74f1363d-5c15-4018-b8e7-a70438ccd184.png)
Para:
![image](https://user-images.githubusercontent.com/55040458/184791181-68fbf8c9-a133-49b7-8fef-ee98540f3911.png)

recomendação: utilizar alguma ferramenta da IDE/Editor de texto para encontrar todas as ocorrências da utilização do `any`. No VSCode é possível realizar essa busca através da lupa: 
![image](https://user-images.githubusercontent.com/55040458/184791392-521627b4-ec31-4551-9bd0-87f9d0db5062.png)

**Comment by JhoPhis** [comment]
Olá Luis, eu (João Plínio) e o meu grupo (Luísa Maria e Arthur Hauck) alunos do curso de Sistemas de Informação da Universidade Federal de Lavras gostariamos de contribuir com essa issue.

**Comment by luis-saes** [comment]
> Olá Luis, eu (João Plínio) e o meu grupo (Luísa Maria e Arthur Hauck) alunos do curso de Sistemas de Informação da Universidade Federal de Lavras gostariamos de contribuir com essa issue.

EN: Sup, João, feel free to contribute, looking forward to seeing the results!
PT: Fala João, fique a vontade, ansioso pelos resultados!

**Comment by luis-saes** [comment]
EN: Thanks for the contribution! Awesome work, guys!
PT: Obrigado pela contribuição! Excelente trabalho, pessoal!
