### ISSUE TITLE
Translate README - Traduzir README

### ISSUE THREAD

**Issue by luis-saes** [luis-saes/generic-dashboard#12]
EN:
Translate the `README.md` file to Portuguese.
- Perform the translation using the already created file `README-pt-BR.md`
- Keep the same structure, there is no need to translate images with text
- Translate WIP (Work in progress) to "In Progress".

PT:
Traduzir o arquivo `README.md` para português.
- Realizar a tradução utilizando o arquivo já criado `README-pt-BR.md`
- Manter a mesma estrutura, não há a necessidade de traduzir as imagens com texto
- Traduzir WIP (Work in progress) para "Em Progresso".

**Comment by paulorsv01** [comment]
Olá @luis-saes, eu gostaria de contribuir com a tradução. Posso?

**Comment by luis-saes** [comment]
> Olá @luis-saes, eu gostaria de contribuir com a tradução. Posso?

EN: Sure, Paulo! Go ahead!!!
PT: Com certeza, Paulo! Vá em frente!!

**Comment by paulorsv01** [comment]
Boa noite, @luis-saes.
Fiquei com uma certa dúvida na tradução de dois pontos no README.
- O primeiro seria o título do projeto: seria necessário fazer a tradução de "Generic Dashboard" para "Painel de Controle genérico", ou pode manter como "Generic Dashboard" mesmo?
- O segundo seria no slogan logo abaixo do título no README, onde se lê: "Just a Generic Dashboard". Caso seja para traduzir o título, esse slogan deve ser traduzido também?

**Comment by luis-saes** [comment]
> Boa noite, @luis-saes. Fiquei com uma certa dúvida na tradução de dois pontos no README.
> 
> * O primeiro seria o título do projeto: seria necessário fazer a tradução de "Generic Dashboard" para "Painel de Controle genérico", ou pode manter como "Generic Dashboard" mesmo?

EN: Translate it as "Dashboard Genérica".
PT: Deixe como "Dashboard Genérica".

> * O segundo seria no slogan logo abaixo do título no README, onde se lê: "Just a Generic Dashboard". Caso seja para traduzir o título, esse slogan deve ser traduzido também?

EN: Yes, the slogan should be translated as "Apenas uma Dashboard Genérica".
PT: Sim, o slogan deve ser traduzido como "Apenas uma Dashboard Genérica".
