### ISSUE TITLE
Rename subfolders inside components folder - Renomear subpastas dentro da pasta components

### ISSUE THREAD

**Issue by luis-saes** [luis-saes/generic-dashboard#13]
EN:
The folders inside the `components` folder (`front-end/src/components/`) are capitalized.
- rename folders so all folders inside `front-end/src/components/` are lowercase
- change the imports of the components of these folders, preventing the code from breaking
example:
from:
![image](https://user-images.githubusercontent.com/55040458/184793521-05095b95-63b6-4eb1-bc67-2e7eabac4068.png)
to:
![image](https://user-images.githubusercontent.com/55040458/184793554-47ad7bed-6c63-4349-90ae-0252034ab2e7.png)

PT:
Atualmente, as pastas dentro da pasta `components` (`front-end/src/components/`) estão com a primeira letra maíscula.
- alterar o nome das pastas para todas as pastas dentro de `front-end/src/components/` terem os nomes minúsculos
- alterar os imports dos componentes dessas pastas, evitando com que o código quebre
exemplo:
de:
![image](https://user-images.githubusercontent.com/55040458/184793521-05095b95-63b6-4eb1-bc67-2e7eabac4068.png)
para:
![image](https://user-images.githubusercontent.com/55040458/184793554-47ad7bed-6c63-4349-90ae-0252034ab2e7.png)

**Comment by ElMigu17** [comment]
Ola Luis, eu e mais dois amigos meus (@eribito e @leoamsena) gostariamos de trabalhar nessa issue, nos poderiamos?

**Comment by luis-saes** [comment]
> Ola Luis, eu e mais dois amigos meus (@eribito e @leoamsena) gostariamos de trabalhar nessa issue, nos poderiamos?
EN: For sure. Miguel, go ahead!!
PT: Claro, Miguel, vá em frente!!

**Comment by luis-saes** [comment]
EN: Thanks for the contribution! Awesome work, guys!
PT: Obrigado pela contribuição! Excelente trabalho, pessoal!
