### ISSUE TITLE
Design a new logo for the project - Faça o design de um novo logo para o projeto

### ISSUE THREAD

**Issue by luis-saes** [luis-saes/generic-dashboard#14]
EN:
The current logo is too simplistic and a new logo would be extremely welcome.
- Design a new logo for the project, creativity is welcome.
- Save the logo with `.png` and `.svg` formats.
- Upload the new logo files to the `/images` folder, naming them `new-logo.png` and `new-logo.svg`.

PT:
O atual logo é simplista demais e um novo logo seria extremamente bem-vindo.
- Faça o design de um novo logo para o projeto, criatividade é bem-vinda
- Salve o logo nos formatos `.png` e `.svg`
- Suba os arquivos do novo logo na pasta `/images`, nomeando-os como `new-logo.png` e `new-logo.svg`.

**Comment by Samir-Carvalho** [comment]
Olá @luis-saes, eu gostaria de contribuir com o design da logo, posso?

**Comment by luis-saes** [comment]
> Olá @luis-saes, eu gostaria de contribuir com o design da logo, posso?

EN: Sure, Samir, go ahead!!
PT: Com certeza, Samir, vá em frente!!
