### ISSUE TITLE
Redirect to /login - Redirecionar para /login

### ISSUE THREAD

**Issue by luis-saes** [luis-saes/generic-dashboard#9]
EN:
Currently, when accessing the site main page (`localhost:3000/`), no screen is displayed.
- change this behavior to automatically access the login page (`localhost:3000/login`)
- use the already installed `react-router-dom` dependency

PT:
Atualmente, ao acessar a página principal do site (`localhost:3000/`), nenhuma tela é exibida.
- alterar esse comportamento para acessar automaticamente a página de login (`localhost:3000/login`)
- utilizar a dependência já instalada `react-router-dom`

**Comment by pullingoff** [comment]
Hi Luis, I'm Hailey.
I'm interested in solving this issue. May I?

**Comment by luis-saes** [comment]
> Hi Luis, I'm Hailey. I'm interested in solving this issue. May I?

Sure, Hailey, go for it!!
